import { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translationDict = {
  en: {
    navHome: "Home",
    navDetect: "Detect",
    navHistory: "History",
    navDashboard: "Dashboard",
    navHub: "Farmer Hub",
    navChatbot: "Farmer AI Chat",
    navAbout: "About",
    analyzePlant: "Analyze Plant",
    heroBadge: "AI-Powered Smart Farming",
    heroTitlePrefix: "Empowering Farmers with",
    heroTitleSuffix: "AI Technology",
    heroSubtitle: "Instantly diagnose plant diseases, check real-time local weather forecasts, explore government schemes, analyze soil characteristics, monitor crop calendars, and chat with our farming AI assistant.",
    selectLanguage: "Language",
    weatherTitle: "Weather Forecast",
    weatherAdvice: "Agricultural Advice",
    temp: "Temperature",
    humidity: "Humidity",
    rain: "Rain Chance",
    wind: "Wind Speed",
    enterCity: "Enter City Name",
    search: "Search",
    govSchemes: "Government Schemes",
    selectState: "Select State",
    soilInfo: "Soil Advisor",
    selectSoil: "Select Soil Type",
    soilAdvantages: "Advantages",
    soilCrops: "Suitable Crops",
    soilFertilizer: "Recommended Fertilizer",
    soilWater: "Water Holding Capacity",
    cropCalendar: "Crop Calendar",
    selectCrop: "Select Crop",
    sowingPeriod: "Sowing Period",
    harvestPeriod: "Harvesting Period",
    mandiPrices: "Mandi Market Prices",
    mandiName: "Market (Mandi)",
    mandiCrop: "Crop",
    mandiPrice: "Price",
    mandiArrival: "Arrival Volume",
    chatbotTitle: "Farmer AI Chatbot",
    chatbotPlaceholder: "Ask me about crop diseases, fertilizers, sowing, water...",
    send: "Send",
    quickQuestions: "Quick Questions",
    totalPredictions: "Total Predictions",
    healthyCount: "Healthy Plants",
    diseasedCount: "Diseased Plants",
    commonDisease: "Most Common Disease",
    severityTitle: "Severity Distribution",
    historyTitle: "Prediction History",
    historySub: "All your past plant disease analyses",
    noHistory: "No history found. Try analyzing a plant!",
    aboutTitle: "About Smart Farmer Assistant",
    treatmentImprovement: "Treatment & Fertilizer Tips"
  },
  hi: {
    navHome: "मुख्य पृष्ठ",
    navDetect: "रोग पहचानें",
    navHistory: "इतिहास",
    navDashboard: "डैशबोर्ड",
    navHub: "किसान हब",
    navChatbot: "किसान एआई चैट",
    navAbout: "हमारे बारे में",
    analyzePlant: "जांच शुरू करें",
    heroBadge: "एआई-संचालित स्मार्ट खेती",
    heroTitlePrefix: "किसानों का सशक्तिकरण",
    heroTitleSuffix: "एआई तकनीक से",
    heroSubtitle: "पौधों के रोगों की तुरंत पहचान करें, स्थानीय मौसम का हाल देखें, सरकारी योजनाओं को जानें, मिट्टी का विश्लेषण करें, फसल कैलेंडर देखें और हमारे खेती एआई सहायक से बातचीत करें।",
    selectLanguage: "भाषा चुनें",
    weatherTitle: "मौसम का पूर्वानुमान",
    weatherAdvice: "कृषि संबंधी सलाह",
    temp: "तापमान",
    humidity: "आर्द्रता",
    rain: "बारिश की संभावना",
    wind: "हवा की गति",
    enterCity: "शहर का नाम दर्ज करें",
    search: "खोजें",
    govSchemes: "सरकारी योजनाएं",
    selectState: "राज्य चुनें",
    soilInfo: "मिट्टी सलाहकार",
    selectSoil: "मिट्टी का प्रकार चुनें",
    soilAdvantages: "फायदे",
    soilCrops: "उपयुक्त फसलें",
    soilFertilizer: "अनुशंसित उर्वरक (खाद)",
    soilWater: "जल धारण क्षमता",
    cropCalendar: "फसल कैलेंडर",
    selectCrop: "फसल चुनें",
    sowingPeriod: "बुवाई का समय",
    harvestPeriod: "कटाई का समय",
    mandiPrices: "मंडी के भाव",
    mandiName: "मंडी का नाम",
    mandiCrop: "फसल",
    mandiPrice: "भाव (₹/क्विंटल)",
    mandiArrival: "कुल आवक",
    chatbotTitle: "किसान एआई चैटबॉट",
    chatbotPlaceholder: "मुझसे फसलों के रोग, खाद, बुवाई, या सिंचाई के बारे में पूछें...",
    send: "भेजें",
    quickQuestions: "त्वरित प्रश्न",
    totalPredictions: "कुल भविष्यवाणियां",
    healthyCount: "स्वस्थ पौधे",
    diseasedCount: "रोगग्रस्त पौधे",
    commonDisease: "सबसे आम बीमारी",
    severityTitle: "गंभीरता का वितरण",
    historyTitle: "जांच का इतिहास",
    historySub: "आपके द्वारा की गई पिछली सभी जांचें",
    noHistory: "कोई इतिहास नहीं मिला। एक पौधे की जांच करके देखें!",
    aboutTitle: "स्मार्ट किसान सहायक के बारे में",
    treatmentImprovement: "उपचार और खाद के टिप्स"
  },
  bho: {
    navHome: "मुख्य पन्ना",
    navDetect: "बीमारी पहचानीं",
    navHistory: "इतिहास",
    navDashboard: "डैशबोर्ड",
    navHub: "किसान हब",
    navChatbot: "किसान एआई बात-चीत",
    navAbout: "हमरे बारे में",
    analyzePlant: "जांच करीं",
    heroBadge: "एआई-आधारित स्मार्ट खेती",
    heroTitlePrefix: "किसान भाई लोगन खातिर",
    heroTitleSuffix: "एआई तकनीक",
    heroSubtitle: "पेड़-पौधा के बीमारी तुंरत पहचानीं, मौसम के हाल देखीं, सरकारी योजना जानीं, मट्टी के जांच करीं आ किसान एआई से बात-चीत करीं।",
    selectLanguage: "भाषा",
    weatherTitle: "मौसम के हाल",
    weatherAdvice: "खेती-बारी के सलाह",
    temp: "तापमान",
    humidity: "नमी",
    rain: "पानी बरसे के चांस",
    wind: "हवा के रफ्तार",
    enterCity: "शहर के नाम लिखीं",
    search: "खोजल जाए",
    govSchemes: "सरकारी योजना",
    selectState: "राज्य चुनीं",
    soilInfo: "मट्टी सलाहकार",
    selectSoil: "मट्टी के प्रकार चुनीं",
    soilAdvantages: "फायदा",
    soilCrops: "फायदेमंद फसल",
    soilFertilizer: "कौन खाद चाही",
    soilWater: "पानी सोखे के क्षमता",
    cropCalendar: "फसल कैलेंडर",
    selectCrop: "फसल चुनीं",
    sowingPeriod: "बोवाई के समय",
    harvestPeriod: "कटाई के समय",
    mandiPrices: "मंडी के दाम",
    mandiName: "मंडी के नाम",
    mandiCrop: "फसल",
    mandiPrice: "दाम (₹/क्विंटल)",
    mandiArrival: "कुल आवक",
    chatbotTitle: "किसान एआई चैटबॉट",
    chatbotPlaceholder: "खाद, बोवाई, पानी या पेड़ के बीमारी के बारे में पूछीं...",
    send: "भेजीं",
    quickQuestions: "तुरंत पूछे वाला सवाल",
    totalPredictions: "कुल जांच",
    healthyCount: "बढ़िया पौधा",
    diseasedCount: "रोगी पौधा",
    commonDisease: "सबसे बेसी होवे वाला रोग",
    severityTitle: "गंभीरता",
    historyTitle: "जांच के इतिहास",
    historySub: "रउवा पुरान सारा जांच के रिकॉर्ड",
    noHistory: "कवनो इतिहास नइखे मिलल। पौधा के जांच करीं!",
    aboutTitle: "स्मार्ट किसान सहायक के बारे में",
    treatmentImprovement: "इलाज आ खाद के सलाह"
  },
  mr: {
    navHome: "मुख्यपृष्ठ",
    navDetect: "रोग ओळखा",
    navHistory: "इतिहास",
    navDashboard: "डॅशबोर्ड",
    navHub: "शेतकरी हब",
    navChatbot: "शेतकरी एआय चॅट",
    navAbout: "आमच्याबद्दल",
    analyzePlant: "तपासणी करा",
    heroBadge: "एआय-आधारित स्मार्ट शेती",
    heroTitlePrefix: "शेतकऱ्यांचे सक्षमीकरण",
    heroTitleSuffix: "एआय तंत्रज्ञानाने",
    heroSubtitle: "झाडांच्या रोगांचे त्वरित निदान करा, हवामान अंदाज पहा, सरकारी योजना शोधा, मातीची माहिती मिळवा आणि आमच्या शेतकरी एआय सहाय्यकाशी संवाद साधा.",
    selectLanguage: "भाषा निवडा",
    weatherTitle: "हवामान अंदाज",
    weatherAdvice: "कृषी सल्ला",
    temp: "तापमान",
    humidity: "आर्द्रता",
    rain: "पावसाची शक्यता",
    wind: "वाऱ्याचा वेग",
    enterCity: "शहराचे नाव टाका",
    search: "शोधा",
    govSchemes: "सरकारी योजना",
    selectState: "राज्य निवडा",
    soilInfo: "मृदा सल्लागार",
    selectSoil: "मातीचा प्रकार निवडा",
    soilAdvantages: "फायदे",
    soilCrops: "योग्य पिके",
    soilFertilizer: "शिफारस केलेले खत",
    soilWater: "जलधारण क्षमता",
    cropCalendar: "पीक कॅलेंडर",
    selectCrop: "पीक निवडा",
    sowingPeriod: "पेरणीचा काळ",
    harvestPeriod: "कापणीचा काळ",
    mandiPrices: "मंडीचे भाव",
    mandiName: "बाजार (मंडी)",
    mandiCrop: "पीक",
    mandiPrice: "दर (₹/क्विंटल)",
    mandiArrival: "एकूण आवक",
    chatbotTitle: "शेतकरी एआय चॅटबॉट",
    chatbotPlaceholder: "मला खते, पेरणी, पाणी किंवा रोगांबद्दल विचारा...",
    send: "पाठवा",
    quickQuestions: "पटकन विचारण्याचे प्रश्न",
    totalPredictions: "एकूण तपासण्या",
    healthyCount: "निरोगी झाडे",
    diseasedCount: "रोगी झाडे",
    commonDisease: "सर्वात सामान्य रोग",
    severityTitle: "तीव्रता वितरण",
    historyTitle: "तपासणी इतिहास",
    historySub: "तुमचे सर्व मागील तपासणी रेकॉर्ड",
    noHistory: "इतिहास सापडला नाही. झाडाची तपासणी करून पहा!",
    aboutTitle: "स्मार्ट शेतकरी सहाय्यकाबद्दल",
    treatmentImprovement: "उपचार आणि खतांचा सल्ला"
  },
  ta: {
    navHome: "முகப்பு",
    navDetect: "நோய் கண்டறிதல்",
    navHistory: "வரலாறு",
    navDashboard: "டாஷ்போர்டு",
    navHub: "விவசாய மையம்",
    navChatbot: "விவசாயி AI சாட்",
    navAbout: "எங்களைப் பற்றி",
    analyzePlant: "ஆராய்ந்து பார்",
    heroBadge: "AI-ஆற்றல் கொண்ட விவசாயம்",
    heroTitlePrefix: "விவசாயிகளை மேம்படுத்தும்",
    heroTitleSuffix: "AI தொழில்நுட்பம்",
    heroSubtitle: "தாவர நோய்களை உடனடியாகக் கண்டறியவும், வானிலை நிலவரங்களை அறியவும், அரசுத் திட்டங்களை ஆராயவும், மண் வகைகளை அறியவும், எங்களது AI உதவியாளருடன் உரையாடவும்.",
    selectLanguage: "மொழியைத் தேர்ந்தெடு",
    weatherTitle: "வானிலை முன்னறிவிப்பு",
    weatherAdvice: "விவசாய ஆலோசனை",
    temp: "வெப்பநிலை",
    humidity: "ஈரப்பதம்",
    rain: "மழைக்கான வாய்ப்பு",
    wind: "காற்றின் வேகம்",
    enterCity: "நகரத்தின் பெயரை உள்ளிடவும்",
    search: "தேடு",
    govSchemes: "அரசு திட்டங்கள்",
    selectState: "மாநிலத்தைத் தேர்ந்தெடு",
    soilInfo: "மண் ஆலோசகர்",
    selectSoil: "மண் வகையைத் தேர்ந்தெடு",
    soilAdvantages: "நன்மைகள்",
    soilCrops: "பொருத்தமான பயிர்கள்",
    soilFertilizer: "பரிந்துரைக்கப்பட்ட உரம்",
    soilWater: "நீர் சேமிப்பு திறன்",
    cropCalendar: "பயிர் காலண்டர்",
    selectCrop: "பயிரைத் தேர்ந்தெடு",
    sowingPeriod: "விதைப்பு காலம்",
    harvestPeriod: "அறுவடை காலம்",
    mandiPrices: "மண்டி சந்தை விலைகள்",
    mandiName: "சந்தை (மண்டி)",
    mandiCrop: "பயிர்",
    mandiPrice: "விலை (₹/குவிண்டால்)",
    mandiArrival: "வரத்து அளவு",
    chatbotTitle: "விவசாயி AI சாட்பாட்",
    chatbotPlaceholder: "பயிர் நோய்கள், உரங்கள், விதைப்பு பற்றி கேளுங்கள்...",
    send: "அனுப்பு",
    quickQuestions: "விரைவான கேள்விகள்",
    totalPredictions: "மொத்த பகுப்பாய்வுகள்",
    healthyCount: "ஆரோக்கியமான தாவரங்கள்",
    diseasedCount: "பாதிக்கப்பட்ட தாவரங்கள்",
    commonDisease: "அதிகப்படியான நோய்",
    severityTitle: "தீவிரத்தன்மை விவரம்",
    historyTitle: "பகுப்பாய்வு வரலாறு",
    historySub: "உங்களது முந்தைய பகுப்பாய்வு தகவல்கள்",
    noHistory: "வரலாறு இல்லை. முதலில் ஒரு தாவரத்தை சோதிக்கவும்!",
    aboutTitle: "விவசாயி AI உதவியாளர் பற்றி",
    treatmentImprovement: "சிகிச்சை மற்றும் உர குறிப்புகள்"
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');

  const t = (key) => {
    return translationDict[lang][key] || translationDict['en'][key] || key;
  };

  const setLanguage = (newLang) => {
    if (translationDict[newLang]) {
      setLang(newLang);
    }
  };

  return (
    <LanguageContext.Provider value={{ lang, t, setLanguage, languages: Object.keys(translationDict) }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useTranslation must be used within a LanguageProvider");
  }
  return context;
}
